config/routes.rb
Rails.application.routes.draw do
  resources :alumno_asignaturas
  resources :horarios
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :aulas
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :asignatura
  belongs_to :aula
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  before_action :set_horario, only: [:show, :edit, :update, :destroy]

  # GET /horarios
  # GET /horarios.json
  def index
    @horarios = Horario.all
  end

  # GET /horarios/1
  # GET /horarios/1.json
  def show
  end

  # GET /horarios/new
  def new
    @horario = Horario.new
  end

  # GET /horarios/1/edit
  def edit
  end

  # POST /horarios
  # POST /horarios.json
  def create
    @horario = Horario.new(horario_params)

    respond_to do |format|
      if @horario.save
        format.html { redirect_to @horario, notice: 'Horario was successfully created.' }
        format.json { render :show, status: :created, location: @horario }
      else
        format.html { render :new }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horarios/1
  # PATCH/PUT /horarios/1.json
  def update
    respond_to do |format|
      if @horario.update(horario_params)
        format.html { redirect_to @horario, notice: 'Horario was successfully updated.' }
        format.json { render :show, status: :ok, location: @horario }
      else
        format.html { render :edit }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horarios/1
  # DELETE /horarios/1.json
  def destroy
    @horario.destroy
    respond_to do |format|
      format.html { redirect_to horarios_url, notice: 'Horario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horario
      @horario = Horario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horario_params
      params.require(:horario).permit(:bloque, :asignatura_id, :aula_id)
    end
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/views/horarios/_form.html.erb
<%= form_with(model: horario, local: true) do |form| %>
  <% if horario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(horario.errors.count, "error") %> prohibited this horario from being saved:</h2>

      <ul>
      <% horario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bloque %>
    <%= form.number_field :bloque %>
  </div>

  <div class="field">
    <%= form.label :asignatura_id %>
    <%= form.text_field :asignatura_id %>
  </div>

  <div class="field">
    <%= form.label :aula_id %>
    <%= form.text_field :aula_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/horarios/edit.html.erb
<h1>Editing Horario</h1>

<%= render 'form', horario: @horario %>

<%= link_to 'Show', @horario %> |
<%= link_to 'Back', horarios_path %>

app/views/horarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Horarios</h1>

<table>
  <thead>
    <tr>
      <th>Bloque</th>
      <th>Asignatura</th>
      <th>Aula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horarios.each do |horario| %>
      <tr>
        <td><%= horario.bloque %></td>
        <td><%= horario.asignatura %></td>
        <td><%= horario.aula %></td>
        <td><%= link_to 'Show', horario %></td>
        <td><%= link_to 'Edit', edit_horario_path(horario) %></td>
        <td><%= link_to 'Destroy', horario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horario', new_horario_path %>

app/views/horarios/new.html.erb
<h1>New Horario</h1>

<%= render 'form', horario: @horario %>

<%= link_to 'Back', horarios_path %>

app/views/horarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bloque:</strong>
  <%= @horario.bloque %>
</p>

<p>
  <strong>Asignatura:</strong>
  <%= @horario.asignatura %>
</p>

<p>
  <strong>Aula:</strong>
  <%= @horario.aula %>
</p>

<%= link_to 'Edit', edit_horario_path(@horario) %> |
<%= link_to 'Back', horarios_path %>